# Generated by Django 2.2.7 on 2020-04-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
