# Generated by Django 2.2.7 on 2020-04-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_color_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='project.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='prefered_color',
            field=models.ForeignKey(default=1, on_delete='None', to='project.Color'),
            preserve_default=False,
        ),
    ]
