# Generated by Django 2.2.7 on 2020-04-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200417_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='color',
            field=models.ForeignKey(default=1, on_delete='None', to='project.Color'),
            preserve_default=False,
        ),
    ]
