# Generated by Django 2.2.7 on 2020-04-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_clothing_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
