# Generated by Django 2.2.7 on 2020-04-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200428_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='size',
            field=models.ForeignKey(default=1, on_delete='None', to='project.Size'),
            preserve_default=False,
        ),
    ]
