# Generated by Django 2.2.7 on 2020-04-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_clothing_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donated_Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('color', models.ForeignKey(on_delete='None', to='project.Color')),
                ('donator', models.ForeignKey(on_delete='None', to='project.Customer')),
                ('size', models.ForeignKey(on_delete='None', to='project.Size')),
            ],
        ),
    ]
