# Generated by Django 2.2.7 on 2020-04-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_donated_clothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Customer'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, upload_to='')),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Donated_Clothing')),
            ],
        ),
    ]
